# Generated by Django 5.1.8 on 2025-11-25 23:23

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("website", "0256_inviteorganization"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name="issue",
            index=models.Index(fields=["cve_id"], name="issue_cve_id_idx"),
        ),
        migrations.AddIndex(
            model_name="issue",
            index=models.Index(fields=["cve_score"], name="issue_cve_score_idx"),
        ),
    ]
