# Generated by Django 5.1.8 on 2025-11-26 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("website", "0257_add_cve_indexes"),
    ]

    operations = [
        migrations.AlterField(
            model_name="issue",
            name="cve_score",
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True),
        ),
    ]
