# Generated by Django 5.1.8 on 2025-11-26 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("website", "0258_fix_cve_score_max_digits"),
    ]

    operations = [
        migrations.AlterField(
            model_name="issue",
            name="cve_id",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
